#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Secure Keys
environment:
  AWS_REGION:
    secure: TpI8eZAA7xTwppMUnUWS4Q==
  AWS_ACCESS_KEY_ID:
    secure: yJis6I3pszTK31O9zFy0CyF5olds8dOSezJlo1Zw+ck=
  AWS_SECRET_ACCESS_KEY:
    secure: OFWhVroAO+2nqG6zGnS1a/1QueNA6ZRf80eqHy64FbOZ3poeSsjS/zD05/vzSyee
  GitHubKey:
    secure: 8rcm5QQdAIatmWWsxw1Evd3mw4p3GkjcVyIMShjY2mmIrOS546w0coB95z5FGLh0
  NuGetApiKey:
    secure: He4qQ4jNoO9z4GBTLKnok4HoPOJBKnVnRgVbOEJYtEvueiHivUB5NDxw3Ebzt2Ck

# Allow WMF5 (i.e. PowerShellGallery functionality)
image:
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu1804
  - macos

# Version number
version: 0.4.{build}

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  author: AppVeyorCI
  files:
    - .gitignore
    - CHANGELOG.md
    - docs/*
    - README.md
    - RELEASE.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*|skip ci/

for:
  - matrix:
      only:
        - image: Visual Studio 2017
    build: off
    init:
      - ps: $PSVersionTable
      - ps: 'Write-Host "Current Location: $(Get-Location)"'
      - ps: Get-Module -ListAvailable | Select-Object -Property Name,Version | Sort-Object -Property Name | Format-Table
    install:
      - ps: '& ./install_modules.ps1'
    test_script:
      - ps: Invoke-Build

build: off
init:
  - pwsh: '& git config --global core.autocrlf true'
  - pwsh: $PSVersionTable
  - pwsh: 'Write-Host "Current Location: $(Get-Location)"'
  - pwsh: Get-Module -ListAvailable | Select-Object -Property Name,Version | Sort-Object -Property Name | Format-Table
install:
  - pwsh: '& ./install_modules.ps1'
test_script:
  - pwsh: Invoke-Build

#on_success:
#  - ps: Invoke-Expression .\appveyor_success.ps1