#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Secure Keys
environment:
  NuGetApiKey:
    secure: He4qQ4jNoO9z4GBTLKnok4HoPOJBKnVnRgVbOEJYtEvueiHivUB5NDxw3Ebzt2Ck
  GitHubKey:
    secure: 8rcm5QQdAIatmWWsxw1Evd3mw4p3GkjcVyIMShjY2mmIrOS546w0coB95z5FGLh0

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Version number
version: 1.0.{build}

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
  - ps: Install-Module -Name InvokeBuild,PSDepend -Force

build: false

test_script:
  - ps: $ErrorActionPreference = 'Stop'
  - ps: Invoke-Build

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
  - git config --global user.name "Andrew Pearce"
  - git config --global user.email "andrew@austoonz.net"
  - ps: Copy-Item -Path .\Artifacts\Convert.psd1 -Destination .\Convert\Convert.psd1
  - git add .\Convert\Convert.psd1
  - git commit "Module Manifest updated (skip ci)"
  - git push