#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Secure Keys
environment:
  GitHubKey:
    secure: 8rcm5QQdAIatmWWsxw1Evd3mw4p3GkjcVyIMShjY2mmIrOS546w0coB95z5FGLh0
  NuGetApiKey:
    secure: He4qQ4jNoO9z4GBTLKnok4HoPOJBKnVnRgVbOEJYtEvueiHivUB5NDxw3Ebzt2Ck

image:
  - macos

# Version number
version: 0.6.{build}

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  author: AppVeyorCI
  files:
    - .gitignore
    - CHANGELOG.md
    - docs/*
    - README.md
    - RELEASE.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*|skip ci/

build: off
init:
  - pwsh: '& git config --global core.autocrlf true'
  - pwsh: $PSVersionTable
  - pwsh: 'Write-Host "Current Location: $(Get-Location)"'
install:
  - pwsh: '& ./install_modules.ps1'
test_script:
  - pwsh: Invoke-Build
