#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Secure Keys
environment:
  NuGetApiKey:
    secure: He4qQ4jNoO9z4GBTLKnok4HoPOJBKnVnRgVbOEJYtEvueiHivUB5NDxw3Ebzt2Ck
  GitHubKey:
    secure: 8rcm5QQdAIatmWWsxw1Evd3mw4p3GkjcVyIMShjY2mmIrOS546w0coB95z5FGLh0

# Allow WMF5 (i.e. PowerShellGallery functionality)
image:
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu1804
  - macos

# Version number
version: 0.4.{build}

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  author: AppVeyorCI
  files:
    - .gitignore
    - CHANGELOG.md
    - docs/*
    - README.md
    - RELEASE.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*|skip ci/

for:
  - matrix:
      only:
        - image: Visual Studio 2017
    init:
      - ps: $PSVersionTable
    install:
      - ps: Install-PackageProvider -Name 'NuGet' -MinimumVersion '2.8.5.201' -Force | Out-Null
      - ps: Install-Module -Name AWSPowerShell,InvokeBuild,posh-git,Pester,platyPS,PSScriptAnalyzer -Force -SkipPublisherCheck
    build_script:
      - ps: Invoke-Build -File .\src\<%=$PLASTER_PARAM_ModuleName%>.build.ps1

init:
  - pwsh: '& git config --global core.autocrlf true'
  - pwsh: $PSVersionTable

install:
  - ps: Install-PackageProvider -Name 'NuGet' -MinimumVersion '2.8.5.201' -Force | Out-Null
  - ps: Install-Module -Name AWSPowerShell.NetCore,InvokeBuild,posh-git,Pester,platyPS,PSScriptAnalyzer -Force -SkipPublisherCheck

#build: off

test_script:
  - pwsh: $ErrorActionPreference = 'Stop'
  - pwsh: Invoke-Build

#on_success:
#  - ps: Invoke-Expression .\appveyor_success.ps1