version: 0.2

env:
  variables:
    POWERSHELL_MSI: PowerShell-6.2.3-win-x64.msi

phases:

  install:
    commands:
      - powershell -command '$PSVersionTable'
      - powershell -command '.\configure_aws_credential.ps1'
      - powershell -command '.\install_modules.ps1'

      # Install PowerShell Core
      - aws s3 cp s3://austoonz-software/$POWERSHELL_MSI $POWERSHELL_MSI --quiet
      - powershell -command "Start-Process -FilePath .\$env:POWERSHELL_MSI -ArgumentList '/qn /norestart' -Wait"
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''$PSVersionTable'''
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''.\install_modules.ps1'''

  build:
    commands:
      - powershell -command 'Invoke-Build'
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''Invoke-Build'''

artifacts:
  files:
    - '**/*'
  base-directory: 'DeploymentArtifacts'