version: 0.2

phases:

  install:
    commands:
      - curl -Ls -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.0.1/powershell-7.0.1-linux-x64.tar.gz
      - mkdir -p /opt/microsoft/powershell/7
      - tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
      - chmod +x /opt/microsoft/powershell/7/pwsh
      - ln -s -f /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

  pre_build:
    commands:
      - pwsh -command '$PSVersionTable'
      - pwsh -command './configure_aws_credential.ps1'
      - pwsh -command './install_modules.ps1'

  build:
    commands:
      - pwsh -command 'Invoke-Build'

artifacts:
  files:
    - '**/*'
  base-directory: 'DeploymentArtifacts'